stages:
  - dependencies
  - lint
  - build
  - release

build dependencies:
  stage: dependencies
  image: alpine/helm:3.10.1
  script:
    - helm dependencies build
  artifacts:
    name: dependencies
    paths:
      - charts/*
      - Chart.lock

lint:
  stage: lint
  image: alpine/helm:3.10.1
  script:
    - helm lint
  needs:
    - build dependencies

package chart:
  stage: build
  image: alpine/helm:3.10.1
  script:
    - helm package .
  needs:
    - build dependencies
    - lint
  artifacts:
    name: Helm package
    paths:
      - "*.tgz"

upload to gitlab:
  stage: release
  image: curlimages/curl:latest
  script:
    - | 
      PACKAGE=$(ls *.tgz);
      curl --request POST \
        --user gitlab-ci-token:$CI_JOB_TOKEN \
        --form "chart=@${PACKAGE}" \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"
  needs:
    - package chart