apiVersion: v2
name: "ctfd"
description: "A chart to deploy a CTFd instance on Kubernetes."

type: application

# This is the chart version. It is expected to follow semver.
version: 0.2.1

# The CTFd version.
# It does not need to follow semver
appVersion: 3.5.3

keywords:
  - ctf
  - capture the flag
  - competition
  - game
  - cybersecurity
  - challenge
home: https://github.com/HackademINT/CTFd-chart
sources:
  - https://github.com/HackademINT/CTFd-chart
  - https://github.com/CTFd/CTFd
icon: https://raw.githubusercontent.com/CTFd/CTFd/master/CTFd/themes/core/static/img/logo.png

maintainers:
  - name: Smyler
    email: smyler@hackademint.org
    url: https://github.com/SmylerMC
  - name: Soremo
    email: soremo@hackademint.org
    url: https://github.com/Soremojinsen

dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.4.x
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.8.x