apiVersion: v2
name: "ctfd"
description: "A chart to deploy a CTFd instance on Kubernetes."

type: application

# This is the chart version. It is expected to follow semver.
version: 0.1.0

# The CTFd version.
# It does not need to follow semver
appVersion: 3.5.3

dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.4.x
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.8.x