hostname: example.com

ctfd:
  security:
    sessionCookie:
      httpOnly: true
      sameSite: "Lax"
    permanentSessionLifetime: 604800
  email:
    addressFrom: ""
    server: ""
    port: ""
    useAuth: true
    username: ""
    password: ""
    tls: ""
    ssl: ""
    addressSender: ""
    mailgun:
      apiKey: ""
      baseUrl: ""
  logFolder: ""
  optional:
    reverseProxy: true
    themeFallback: true
    swaggerUi: false
    updateCheck: true
    serverSentEvents: true
    htmlSanitization: false
    sqlAlchemy:
      trackModifications: false
      maxOverflow: ""
      poolPrePing: ""
    safeMode: false
  oauth:
    clientId: ""
    clientSecret: ""

deployment:
  image:
    image: registry.hackademint.org/hackademint/ctfd/develop:latest
    pullSecret: ""
    pullPolicy: IfNotPresent
  replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true