apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ctfd.fullname" . }}
  labels:
    {{- include "ctfd.labels" . | nindent 4 }}
data:
  security.sessionCookie.httpOnly: {{ .Values.security.sessionCookie.httpOnly | quote }}
  security.sessionCookie.sameSite: {{ .Values.security.sessionCookie.sameSite | quote }}
  security.permanentSessionLifetime: {{ .Values.security.permanentSessionLifetime | quote }}
  email.addressFrom: {{ .Values.email.addressFrom | quote }}
  email.server: {{ .Values.email.server | quote }}
  email.port: {{ .Values.email.port | quote }}
  email.useAuth: {{ .Values.email.useAuth | quote }}
  email.tls: {{ .Values.email.tls | quote }}
  email.ssl: {{ .Values.email.ssl | quote }}
  email.addressSender: {{ .Values.email.addressSender | quote }}
  email.mailgun.baseUrl: {{ .Values.email.mailgun.baseUrl | quote }}
  logFolder: {{ .Values.logFolder | quote }}
  optional.reverseProxy: {{ .Values.optional.reverseProxy | quote }}
  optional.themeFallback: {{ .Values.optional.themeFallback | quote }}
  optional.swaggerUi: {{ .Values.optional.swaggerUi | quote }}
  optional.updateCheck: {{ .Values.optional.updateCheck | quote }}
  optional.serverSentEvents: {{ .Values.optional.serverSentEvents | quote }}
  optional.htmlSanitization: {{ .Values.optional.htmlSanitization | quote }}
  optional.sqlAlchemy.maxOverflow: {{ .Values.optional.sqlAlchemy.maxOverflow | quote }}
  optional.sqlAlchemy.trackModifications: {{ .Values.optional.sqlAlchemy.trackModifications | quote }}
  optional.sqlAlchemy.poolPrePing: {{ .Values.optional.sqlAlchemy.poolPrePing | quote }}
  optional.safeMode: {{ .Values.optional.safeMode | quote }}