apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ctfd.fullname" . }}
  labels:
    {{- include "ctfd.labels" . | nindent 4 }}
  annotations:
    checksum/ctfd-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    checksum/ctfd-secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "ctfd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ctfd.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ctfd
          image: {{ .Values.deployment.image.image | quote }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: flaskSecretKey
                  name: {{ include "ctfd.fullname" . }}
            - name: SESSION_COOKIE_HTTPONLY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: security.sessionCookie.httpOnly
            - name: SESSION_COOKIE_SAMESITE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: security.sessionCookie.sameSite
            - name: PERMANENT_SESSION_LIFETIME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: security.permanentSessionLifetime
            - name: MAILFROM_ADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: email.addressFrom
            - name: MAIL_SERVER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: email.server
            - name: MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: email.port
            - name: MAIL_USEAUTH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: email.useAuth
            {{- if .Values.ctfd.email.useAuth }}
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: emailUsername
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: emailPassword
            {{- end }}
            - name: MAIL_TLS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: email.tls
            - name: MAIL_SSL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: email.ssl
            - name: MAILSENDER_ADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: email.addressSender
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: mailgunApiKey
            - name: MAILGUN_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: email.mailgun.baseUrl
            - name: LOG_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: logFolder
            - name: REVERSE_PROXY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: optional.reverseProxy
            - name: THEME_FALLBACK
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: optional.themeFallback
            - name: TEMPLATES_AUTO_RELOAD
              value: "false"
            - name: SQLALCHEMY_TRACK_MODIFICATIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: optional.sqlAlchemy.trackModifications
            - name: SWAGGER_UI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: optional.swaggerUi
            - name: UPDATE_CHECK
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: optional.updateCheck
            - name: SERVER_SENT_EVENTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: optional.serverSentEvents
            - name: HTML_SANITIZATION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: optional.htmlSanitization
            - name: SQLALCHEMY_MAX_OVERFLOW
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: optional.sqlAlchemy.maxOverflow
            - name: SQLALCHEMY_POOL_PRE_PING
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: optional.sqlAlchemy.poolPrePing
            - name: SAFE_MODE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: optional.safeMode
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: oauthClientId
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "ctfd.fullname" . }}
                  key: oauthClientSecret
          ports:
            - containerPort: 8000
      {{- if .Values.deployment.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.deployment.image.pullSecret | quote}}
      {{- end }}