{{- if and .Values.externalRedis.enabled ( not .Values.externalRedis.existingSecret ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctfd.redis.redisSecretName" . }}
  labels:
      {{- include "ctfd.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.externalRedis.password | b64enc | quote }}
{{- end -}}