{{- if and .Values.externalDatabase.enabled ( not .Values.externalDatabase.existingSecret ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctfd.maridb.databaseSecretName" . }}
  labels:
      {{- include "ctfd.labels" . | nindent 4 }}
type: Opaque
data:
  accessKey: {{ .Values.externalS3.accessKey | b64enc | quote }}
  secretKey: {{ .Values.externalS3.secretKey | b64enc | quote }}
{{- end -}}