apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctfd.fullname" . }}
  labels:
      {{- include "ctfd.labels" . | nindent 4 }}
type: Opaque
data:
  flaskSecretKey: {{ include "ctfd.secret.flaskSecretKey" . | b64enc | quote }}
  {{- if and .Values.mail.smtp.enabled .Values.mail.smtp.useAuth }}
  smtpUsername: {{ include "ctfd.secret.smtp.username" . | b64enc | quote }}
  smtpPassword: {{ include "ctfd.secret.smtp.password" . | b64enc | quote }}
  {{- else if .Values.mail.mailgun.enabled }}
  mailgunApiKey: {{ include "ctfd.secret.mailgun.apiKey" . | b64enc | quote }}
  {{- end }}
  oauthClientId: {{ include "ctfd.secret.oauth.clientId" . | b64enc | quote }}
  oauthClientSecret: {{ include "ctfd.secret.oauth.clientSecret" . | b64enc | quote }}
