apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctfd.fullname" . }}
  labels:
      {{- include "ctfd.labels" . | nindent 4 }}
type: Opaque
data:
  flaskSecretKey: {{ include "ctfd.secret.flaskSecretKey" . | b64enc | quote }}
  {{- if .Values.ctfd.email.useAuth }}
  emailUsername: {{ include "ctfd.secret.email.username" . | b64enc | quote }}
  emailPassword: {{ include "ctfd.secret.email.password" . | b64enc | quote }}
  {{- end }}
  mailgunApiKey: {{ include "ctfd.secret.email.mailgun.apiKey" . | b64enc | quote }}
  oauthClientId: {{ include "ctfd.secret.oauth.clientId" . | b64enc | quote }}
  oauthClientSecret: {{ include "ctfd.secret.oauth.clientSecret" . | b64enc | quote }}